import {
  BarChart3,
  Workflow,
  ShieldCheck,
  Smartphone,
  Plug,
  Boxes,
  Code2,
  Zap,
  Lock,
  TrendingUp,
  Users2,
  Award,
  HeartHandshake,
  Globe2,
  Headset,
  Rocket,
  PenTool,
  Compass,
  Wrench,
  Lightbulb,
  ClipboardList,
  Hammer,
  TestTube2,
  LifeBuoy,
  Brain,
  Settings,
  ListChecks,
  Database,
  type LucideIcon,
} from "lucide-react";

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  "bar-chart-3": BarChart3,
  workflow: Workflow,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  plug: Plug,
  boxes: Boxes,
  "code-2": Code2,
  zap: Zap,
  lock: Lock,
  "trending-up": TrendingUp,
  users: Users2,
  award: Award,
  "heart-handshake": HeartHandshake,
  globe: Globe2,
  headset: Headset,
  rocket: Rocket,
  "pen-tool": PenTool,
  compass: Compass,
  wrench: Wrench,
  lightbulb: Lightbulb,
  "clipboard-list": ClipboardList,
  hammer: Hammer,
  "test-tube": TestTube2,
  "life-buoy": LifeBuoy,
  brain: Brain,
  settings: Settings,
  "list-checks": ListChecks,
  database: Database,
};

export function resolveIcon(key: string | undefined, fallback: LucideIcon = Code2): LucideIcon {
  if (!key) return fallback;
  return ICON_REGISTRY[key] ?? fallback;
}
